### ISSUE TITLE
Android 12 - markup app crashes with autofill plugin running

### ISSUE THREAD

**Issue by networxnet** [PhilippC/kp2a_accservice_autofill#37]
After yesterday's update to android 12 on my pixel 4a Google markup app for editing screenshots is crashing on access.

Creat screenshot and then press the pencil icon for editing, markup app starts and immediately force close. In safe mode it works. 

So I deactivate app by app 🙄 after stoping autofill plugin markup is working again.

You can avoid crash if you immediately choose an pen in markup app after start bit you must be very very quick <0.2 sec.. may be this info helps with cause analysis.

Logcat entry is: FATAL EXCEPTION: main Process: com.google.android.markup, PID: 25699 java.util.UnknownFormatConversionException: Conversion = 'End of String' at java.util.Formatter$FormatSpecifierParser.peek(Formatter.java:2642) at java.util.Formatter$FormatSpecifierParser.<init>(Formatter.java:2603) at java.util.Formatter.parse(Formatter.java:2558) at java.util.Formatter.format(Formatter.java:2505) at java.util.Formatter.format(Formatter.java:2459) at java.lang.String.format(String.java:2911) at android.content.res.Resources.getString(Resources.java:562) at uy.u(PG:14) at uy.x(PG:8) at uy.k(PG:11) at ux.a(PG:1) at gn.createAccessibilityNodeInfo(PG:1) at android.view.AccessibilityInteractionController.populateAccessibilityNodeInfoForView(AccessibilityInteractionController.java:403) at android.view.AccessibilityInteractionController.findAccessibilityNodeInfoByAccessibilityIdUiThread(AccessibilityInteractionController.java:358) at android.view.AccessibilityInteractionController.access$500(AccessibilityInteractionController.java:74) at android.view.AccessibilityInteractionController$PrivateHandler.handleMessage(AccessibilityInteractionController.java:1547) at android.os.Handler.dispatchMessage(Handler.java:106) at android.os.Looper.loopOnce(Looper.java:201) at android.os.Looper.loop(Looper.java:288) at android.app.ActivityThread.main(ActivityThread.java:7842) at java.lang.reflect.Method.invoke(Native Method) at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548) at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)

**Comment by bin101** [comment]
Can confirm this.
@PhilippC 
Do you think this related to the plugin or otherwise a Markup issue?

**Comment by bin101** [comment]
nvm I think this plugin is obsolete with the autofill suggestions for keyboards provided by Android 11+

**Comment by Spylnw99** [comment]
nvm ฉันคิดว่าปลั๊กอินนี้ล้าสมัยด้วยคำแนะนำป้อนอัตโนมัติสำหรับคีย์บอร์ดที่จัดเตรียมโดย Android 11+

**Comment by Spylnw99** [comment]
nvm ฉันคิดว่าปลั๊กอินนี้ล้าสมัยด้วยคำแนะนำป้อนอัตโนมัติสำหรับคีย์บอร์ดที่จัดเตรียมโดย Android 11+

**Comment by Baumhouse** [comment]
I'm able to confirm this issue. I need to have autofill enabled because of my password manager. Google needs to fix this.
